baseURL = "https://fossix.org"
title = "Fossix"

languageCode = "en-us"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"

theme = "fossix"

[Params]
  custom_css = ["syntax.css"]
  subtitle = "Open Source Matters"
  categories = ["Snippets", "Blogs", "Articles"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
