baseURL = "https://fossix.org"
title = "Fossix"

languageCode = "en-us"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"

theme = "fossix"

pygmentsUseClasses = false

[Params]
  custom_css = ["syntax.css"]
  subtitle = "Open Source Matters"
  categories = ["Snippets", "Blogs", "Articles"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 0
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    tabWidth = 4
